### ISSUE TITLE
Extra Credits Practical Rules

### ISSUE THREAD

**Issue by Manuzor** [lab132/krepel#11]
Hier ist etwas, das wir uns vielleicht alle anschauen sollten: https://www.youtube.com/watch?v=dHMNeNapL1E

Hört sich für mich auf jeden Fall alles sehr vernünftig an...

**Comment by Manuzor** [comment]
Nächste Episode: https://www.youtube.com/watch?v=UvCri1tqIxQ

Die geben dort eine Liste von Genres, sortiert nach der Schwierigkeit sie zu implementieren (einfachstes zuerst):

1. Racing Game
1. Top Down Shooter
1. 2D Platformer
1. Color Matching Puzzle Game
1. 2D Puzzle Platformer
1. 3D Platformer
1. FPS
1. JRPG
1. Fighting Game
1. Action Adventure
1. Western RPG
1. RTS

Point-n-Click Adventures bestehen wohl am meisten aus Content, deswegen sollte man damit erst gar nicht anfangen.

**Comment by juliusf** [comment]
Ich hab mir das Video gestern angesehen. Macht schon Sinn was die da Teilweise von sich geben. 
Bezieht sich diese Liste auf Schwierigkeit des Game Design oder auf Schwierigkeit der Implementierung? 

Von der technischen Seite her würde ich uns jetzt nicht in die Kategorie "Blutige Anfänger" stecken. Dafür haben wir alle schon zu viel Erfahrung.

**Comment by Manuzor** [comment]
Ich denke, die haben dieses Ranking nach dem Gesamtaufwand her erstellt.

Blutige Anfänger sind wir sicher nicht, aber trotzdem müssen wir erst mal einen Workflow etablieren und das lässt sich auch mit einem einfachen Game realisieren. Ich habe dazu schon konkrete Ideen zur Realisierung, aber dazu mehr im Februar, wenn wir uns dann mal treffen. :muscle:
