### ISSUE TITLE
Krepel Meeting 1

### ISSUE THREAD

**Issue by Manuzor** [lab132/krepel#13]
Es ist soweit, die erste (eigentlich zweite) Besprechungsrunde zu Krepel steht an da die Prüfungen so gut wie vorbei sind und wir endlich an unserem Spiel arbeiten wollen!

Doodle: http://doodle.com/tq5v2g2cbymczc6g

Marias letzte Prüfung ist am Montag um 13:00 vorbei, deswegen steht das so im Doodle drin. Bei mir kommt am Donnerstag der Schornsteinfeger zwischen 13:00 und 14:00 Uhr, deswegen kann ich erst ab ca. 15:00.

Die wichtigsten Dinge, die es zu besprechen gilt:

* Extra Credits **Minimum Viable Product**: ob und wie
* Endgültige Entscheidung in Sachen **Genre**
* **Workflow** und **tooling**

**Comment by Manuzor** [comment]
Na, die Begeisterung hält sich bei euch ja in Grenzen :grinning: Woran liegts denn? Könnt ihr euch nicht entscheiden, wann ihr Zeit habt? Bekommt ihr keine Notifications? Sollen wir uns eine andere Kommunikationsmöglichkeit zulegen für kleinere Besprechungen wie z.B. https://slack.com/ oder IRC?

**Comment by juliusf** [comment]
Ne, github ist schon top. Ich habs nur nicht gleich beantwortet und dann vergessen

**Comment by Manuzor** [comment]
Ok :) Dann brauchen wir nur noch zwei weitere Einträge!

**Comment by Manuzor** [comment]
Nur für den Fall, dass der Herr Wohlbrecht seine Notifications aus gemacht hat bzw. keine bekommt: @desmo9k

**Comment by Manuzor** [comment]
Ah! So wie's aussieht, haben sich nun alle eingetragen. Jules scheint am meisten beschäftigt zu sein, deswegen richten wir uns nach dir, würd ich sagen :) Um wie viel Uhr sollen wir uns dann genau treffen? Mir wäre eigentlich alles nach 9:00 recht. Maria (@GretelF) wird da auch nichts dagegen haben, denke ich. Liegt nun an euch beiden @juliusf und @desmo9k.

**Comment by Manuzor** [comment]
Mit "wir richten uns nach Jules" meinte ich natürlich den Tag, an dem Wir uns treffen. Der nächstmögliche Termine wäre demnach Mittwoch.

**Comment by desmo9k** [comment]
Mittwoch ist gut, 9 Uhr ist auch gut. Ab 13 Uhr bin ich dann leider in Besprechungen zum ITFS verhaftet.
Also besser früh als spät aber so lange werde wir ja wahrscheinlich erst mal nicht brauchen.

**Comment by Manuzor** [comment]
Wie lange geht denn die Besprechung? Wenn die nur so 2 Stunden geht, ist's ja nicht so schlimm. Also im Falle, dass wir mehr Zeit brauchen.

**Comment by desmo9k** [comment]
Das kann ich leider nicht sagen. Da kommen eben auch die Veranstalter vom ITFS also könnte es länger gehen.

**Comment by desmo9k** [comment]
Hallo, ich hab jetzt am Mittwoch auch noch um 10 Uhr ne Besprechung mim Kretzschmar.
Er schreibt zwar es wird ne kurze Besprechung aber eine Stunde geht da bestimmt auch nochmal verloren.

Meinungen?

**Comment by Manuzor** [comment]
Also von mir aus können wir uns jetzt morgen einfach mal treffen. Falls uns die Zeit nicht reicht, könnten wir ja einfach am Freitag weitermachen.

**Comment by juliusf** [comment]
09:00 ist okay. ich kann auch nicht all zu viel zeit opfern weil ich grade doch mehr um die ohren habe als gedacht. freitag werde ich vermutlich keine zeit haben

**Comment by juliusf** [comment]
kurze anmerkung: können wir das ganze nicht auch einfach als skype session machen? ich müsste sonst extra für eine Stunde an die HdM gurken.

**Comment by Manuzor** [comment]
Dann lassen wir das doch morgen einfach sein.

Ich würde mich halt gern mit euch physikalisch treffen, damit's nicht so umständlich wird, mal was zu zeigen etc. Wir müssen uns ja nicht ständig in Person treffen.

Also da du ja Freitag auch keine Zeit hast, wie sieht's dann am Samstag aus?

@desmo9k: Gibt's eigentlich noch Kaffee im CA Labor oder sollte man was mitbringen?

**Comment by desmo9k** [comment]
Kaffee ist aus. Wenn ihr ihn nicht braucht wird er im Labor gerne absorbiert.

Ist das alles kompliziert... Samstag beginnt bei mir der Umzug, was aber nichts bedeuten muss.
Wir wollen nur mal zwei oder drei Ladungen Zeug in die andere Wohnung fahren.
Und wenn das für alle passt können wir uns dann auch gerne bei mir in der neuen oder alten Wohnung treffen.

**Comment by Manuzor** [comment]
Wenn's genügend Platz, nen Whiteboard und genügend Stromanschlüsse gibt, dann ist's mir egal, wo wir uns einfinden :smile:

**Comment by desmo9k** [comment]
Whiteboard solltest du dann mitbringen.

**Comment by juliusf** [comment]
bei mir ist grade generell viel zu tun mit thesis und so weil das alles schon wieder länger dauert als ich ursprünglich geplant hatte. ich hab am montag ne besprechung mit meinem betreuer und muss bis dahin noch diverse simulationen durchführen. Wie wäre es denn wenn wir uns einfach am Montag nach meiner präsentation treffen? dann hab ich auch genügend geistige kapazität für wichtige dinge frei ;)

**Comment by Manuzor** [comment]
Im Grunde wäre Montag sehr gut für Maria und mich. Wann ist denn deine Besprechung? Ich hab nämlich um 10:00 einen Termin mit dem Radicke wegen GPP und weiß nicht, wie lange das dauert. Das kann ich aber glaub ich gut steuern.

**Comment by juliusf** [comment]
erst um 14:00. das wird aber maximal eine stunde gehen. danach hätte ich zeit bis open end. zur not können wir eventuell auch was machen dass wir uns schon davor treffen und ich dann halt mal für ne stunde verschwinde

**Comment by Manuzor** [comment]
Aber davor hast ja bestimmt noch kein Kopf für sowas :) Also für mich wäre 15:00 OK denke ich. Das mit dem Radicke geht, wie du ja weißt, gern mal etwas länger.

**Comment by Manuzor** [comment]
Da niemand dagegen war geh ich nun einfach davon aus, dass wir uns morgen um 15:00 Uhr treffen. Bis dann im CA Labor! @desmo9k @GretelF @juliusf

**Comment by desmo9k** [comment]
Jup, geht klar.

**Comment by Manuzor** [comment]
Ich schließ das hier mal. @GretelF Ich sag dir später persönlich, was wir alles besprochen haben :wink:
