### ISSUE TITLE
Sprite Rendering

### ISSUE THREAD

**Issue by juliusf** [lab132/krepel#9]
hey,

ich war grade mal neugierig und hab den rendering branch ausprobiert. Anscheinend gibt es einen kleinen Unterschied zwischen den STDlibs:
renderExtracor.h:
```{.h}
    static byte* s_buffers[2];
    static byte* s_readBuffer;
    static byte* s_writeBuffer;
```
ich krieg nen compiler fehler dass er byte* nicht kennt. 
als einfachen workaround schlage ich ein

```{.cpp}
typedef unsigned char byte;
```
vor.

Es scheint übrigens noch eine dependency im cmake zu ezSystem zu geben:
```
(null): No such file or directory: '/Volumes/HDD/Users/juliusflohr/Dev/ezEngine_manu/Output/Lib/OsxMakeClangDebug64/ezSystem.a'
```
Der compiler weiss zwar dass er das ding nicht mehr bauen soll, nur der linker weiss noch nichts von seinem glück :)

**Comment by Manuzor** [comment]
Ja, das mit dem `byte` hab ich ca. 20 min. später schon gefixt :grinning:

Das mit der ezSystem depdendency hab ich bei mir noch nicht rausgenommen gehabt. Ich fix das gleich.

Allerdings muss ich sagen, es ist schon ein schmerz das SFML window zu benutzen und für den rest ez, weil ez dann nicht den input handlen kann... ich glaub ich probiers mal, das ezSystem CMake zeug zu fixen.

**Comment by Manuzor** [comment]
Hab lokal einiges ausprobiert mit OpenGL rendering. Das werde ich dann in krepel übernehmen.

**Comment by Manuzor** [comment]
Hab den branch `rendering` umbenannt in `sprite-rendering`. Es kommen nämlich noch sachen wie `font-rendering` und `debug-rendering`, aber so lange will ich nicht warten, bis das im `master` landet.

**Comment by Manuzor** [comment]
Hab das Sprite Rendering implementiert. Dokumentation ist schon da, könnte aber mehr sein. Dazu mach ich bald mehr. Für bessere Unit Tests muss man noch eine Art _image diff_ implementieren, damit wir Bilder miteinander vergleichen können. Wie man Sprites erstellt und benutzt kann man in `test_sprite.cpp` im `krEngineTests` Projekt sehen.

Angesichts des neuen Names dieses Tickets schließe ich es mal.
